language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t afnanqureshi/react-test -f ./client/Dockerfile.dev ./client  

script:
#   - docker run -e CI=true afnanqureshi/react-test npm test

# after_success:
  # - docker build -t afnanqureshi/multi-client ./client
  # - docker build -t afnanqureshi/multi-nginx ./nginx
  # - docker build -t afnanqureshi/multi-server ./server
  # - docker build -t afnanqureshi/multi-worker ./worker
  # - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  # - docker push afnanqureshi/multi-client
  # - docker push afnanqureshi/multi-nginx
  # - docker push afnanqureshi/multi-server
  # - docker push afnanqureshi/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi'
  env: 'Multi-env'
  bucket_name: 'elasticbeanstalk-us-east-1-444037826271'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY